{% set version = '0.3' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-config
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/config_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/config/config_{{ version }}.tar.gz
  sha256: 5ade6a768db6225634095ac0e71e5710fd1597c15512bac0b45a0b52afb3c750

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: testthat, knitr
requirements:
  build:
    - {{posix}}zip               # [win]

  host:
    - r-base
    - r-yaml >=2.1.13

  run:
    - r-base
    - r-yaml >=2.1.13

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('config')"           # [not win]
    - "\"%R%\" -e \"library('config')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/rstudio/config
  license: GPL-3
  summary: Manage configuration values across multiple environments (e.g. development, test,
    production). Read values using a function that determines the current environment
    and returns the appropriate value.
  license_family: GPL3

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: config
# Type: Package
# Title: Manage Environment Specific Configuration Values
# Version: 0.3
# Authors@R: c( person("JJ", "Allaire", role = c("aut", "cre"), email = "jj@rstudio.com"), person(family = "RStudio, Inc.", role = "cph"))
# Imports: yaml (>= 2.1.13)
# Suggests: testthat, knitr
# Description: Manage configuration values across multiple environments (e.g. development, test, production). Read values using a function that determines the current environment and returns the appropriate value.
# License: GPL-3
# URL: https://github.com/rstudio/config
# BugReports: https://github.com/rstudio/config/issues
# RoxygenNote: 6.0.1
# VignetteBuilder: knitr
# NeedsCompilation: no
# Packaged: 2018-03-27 17:50:45 UTC; jjallaire
# Author: JJ Allaire [aut, cre], RStudio, Inc. [cph]
# Maintainer: JJ Allaire <jj@rstudio.com>
# Repository: CRAN
# Date/Publication: 2018-03-27 20:38:53 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
