travis:
  secure:
    BINSTAR_TOKEN: MFBz2LhCE+rmXTxDvCtuE8RocZPWw0QzF7gZsHOuMP+adri7oVGEd8YCaUSnrI19ZpxU7Ymm22QdM7u1yibV9ufJgr8tn3oGKdrVPTHRmtPce35snsAcTcMndw2eUxk6ILGEnTgrZeIN5yEaDge7YIEx1k8ze2a5pe4pfl33v6VDQnqm1NHJSvz3BGQcX3OB30Gv+How1Ih8SH5d+FOeyd7V/ciFRgE57jNfESiycDdEhDwg5rzYPPa47pHjkLK6EFFcqDeBtj5zqjBrVrvH3ah53jC/wUZ3BQcrWU5df6kPGDV2FByAMC581BxXiYz0Bm4FGICt2uTndUZ/j/sBlvKsvkx+qMowD1L0eL/74lZiD+xa2HKi1SVUzFEKkiX8eeMJ29aS8+Fb3AtkCPxkmkzj17EdBENJ4nBjN+XtI6k7H/LA1QUW1PSSA2OggBWG1EWCa/DFKbbDd2O1ciy/WHzd/qDivvPobSVxuDQDnB2SAJxTuszo8gDk1+++nFKGLHEqWzv+3OFny4MY2FlezNV3/k3wvG+KQDz2lG1x0R4VIc9GkLI6zYMTbzCF3PdRPIK2BPsEX5gwaX5snlBK6o09U4nVWzcM9rQiaFqyFcB5f9zpBaGnqUqLVEHEs3CXfBSwHmb9E/YndjKtkdZDeUPlx4S0S6kZoHVzRh5zzUM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
