travis:
  secure:
    BINSTAR_TOKEN: GwJwU/zKIvQowLuer4V4tQVaOyT57P+JdNGkj9vgVL6ui1aVxtL9xWBZDOLJ5nHBO8Q+neleH7GyYPh0j9KLguDe5W35oUa29VrtH1j7TfMjDGNpWFNSOKN/f9jUtLj6goxpmi2Y7Kw640U5u+NQPp4CceEapZK/r3wTpeo8xoc7JscSioolW/tfTewcbXtAt/vqtp5ZGDFNH4KBH0M7wLzSk/+CaUYdDoTTaOfdWBzsSGPcfphycSWAmCzhZ3ftc4fpgzJbTMqPwWD39O+rJpx8r2Sndk+sh+RiOrXU1Ajhw+VEVSDyZOLBKnw+ul1TlMvWm3z9yd8XQMO3LdPY2WcUPO1PmBo6LS+BsnSrVNi0Gq22Zir4ZiiQ/lIqz7LEjx4wLU6p+hLF5NraJ7jMJD70278q3blyRQBSQQjbKj/7cJ8VEiVkcMNu5vDAKATZD91mIz7ur4PrmWQMbW2CPolXPyWUSYZXYq8sTgQtfQP90MHEPZCRYoMy8DBKaGZ3jyE4K+nuHg/IxgeqJ/ET2F4T5fL1h9AynDXBegZtIRgo+DPq50HSGOQkfWnu8nlUUjdu+oSu7eHzu/3rUFdI36WXbZ52GclscYZD0xgu6sfejRa2RHeIvIKKqQ3+43EDmQcavn6MaiT0BGs2BBlgmdLgmZB1Xa+BUjka0cQxVFA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
